### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by frank-dspeed**
Updated dependencys dedupes package versions

### CODE REVIEW

**Comment by chasenlehara** [comment]
Hey @frank-dspeed, I just merged https://github.com/canjs/can-stream-kefir/pull/36 so Greenkeeper should submit PRs to update this project’s dependencies.

**Comment by frank-dspeed** [comment]
@chasenlehara i am not sure if that works as you expect it but if it works its ok. I keep that open till i see a version of can-stream-kefir with current packages and will upgrade packages my self till that lands thanks for taking care :+1:

**Comment by frank-dspeed** [comment]
@chasenlehara importent if we talk about this at same time we should talk about https://github.com/canjs/can-stream as this has the same issues and we get wrong packages there else that are buggy and outdated

**Comment by frank-dspeed** [comment]
@chasenlehara and lets not forget "can-define-stream": "git+https://github.com/frank-dspeed/can-define-stream.git#patch-1",

**Comment by frank-dspeed** [comment]
@phillipskevin no it don't installed the later dependencys thats why i forked and updated this.

**Comment by chasenlehara** [comment]
Thanks @frank-dspeed! This’ll be released next week (I don’t have permission on npm to release this package).

**Comment by frank-dspeed** [comment]
@chasenlehara :+1:  but please don't forget the other related repos situation is exactly the same and i need near same versions i think that logical :)

**Comment by phillipskevin** [comment]
@chasenlehara, I added you to this one in NPM also.

@frank-dspeed, I'm not sure why it's not installing the latest in your project. Make sure you have the latest minor version listed for anything that is < 1.0. For example, if you have `"can-stream": "^0.2.0"` you will not get `can-stream@0.3.0` which will cause dependency problems.

I don't think this module alone is the problem. Here are the dependencies that get installed _prior_ to this Pull Request being merged:
```
can-stream-kefir@0.3.0 /home/kevin/dev/can-stream-kefir
├── can-compute@3.3.0
├── can-define@1.3.2
├── can-event@3.5.0
├── can-observation@3.3.0
├── can-stream@0.3.0
├── can-util@3.9.4
├── done-serve@1.3.0
├── donejs-cli@1.0.2
├── generator-donejs@1.0.6
├── jshint@2.9.5
├── kefir@3.7.2
├── steal@1.5.4
├── steal-qunit@1.0.1
├── steal-tools@1.3.6
└── testee@0.5.1
```

All of these are >= than the versions that are specified in the package.json now (aside from testee).

**Comment by frank-dspeed** [comment]
@phillipskevin i am sure its because the pre tag is not valid semver

**Comment by chasenlehara** [comment]
This has been released in [v0.3.1](https://github.com/canjs/can-stream-kefir/releases/tag/v0.3.1). Thanks again @frank-dspeed!

**Pull request merged**
